spring:
  # PostgreSQL 数据源配置
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:chatAppDB}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:721215}
    driver-class-name: org.postgresql.Driver
  
  # JPA 配置
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  
  # MongoDB 配置
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DBNAME:ChatApp}
      auto-index-creation: true
  
  # MVC 配置
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  
  # 邮件配置
  mail:
    host: smtp.sina.cn
    port: 587
    username: 18669815282m@sina.cn
    password: af69a33fb41618bd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # RabittMQ 配置
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:admin}
    password: ${RABBITMQ_PASSWORD:admin}

# 应用自定义配置
chatroomApp:
  FrontEndURL: ${FRONT_URL:http://localhost:4200}
  jwt:
    secret: dGhpcyBpcyBhIHRlc3Qgc2VjcmV0IGtleSBmb3IgZ2VuZXJhdGUgand0IHRva2Vucw==
    resetPwdTokenExpirationTime: 30
    loginTokenExpirationTime: 120
  rememberMe:
    key: remerber-me
    expirationTime: 604800
  blackListService:
    clearExpiredTokensInterval: 900000

server:
  port: 53050
